services:
   - docker:dind
   
stages:
    - build
    - test
    
build:
    stage: build
    script:
        - docker build -f dockerfile-frontend-server.dev .

test:
    stage: test
    script:
        - echo "testing"