#Travis Config File

services:
  - docker

language: node_js

warnings_are_errors: true

matrix:
  include:
    #Backend Tests
    - language: python
      python: 3.6
      provider: script
      before_script:
        - cd backend/
        - pip install -r requirements.txt
      script:
        - docker-compose run --rm backend ./manage.py test tests

    #APIs Tests (Local Environment Only)
    - language: node_js
      node_js: 10.15
      provider: script
      install:
        - npm install newman
      before_script:
        - docker-compose up -d --build
        - npm install frontend/
        - echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@email.ca', 'Password1234!')" | python manage.py shell
      script:
        - newman run backend/tests/postman/ThunderCAT.postman_collection.json -e backend/tests/postman/environments/local/ThunderCAT.local.postman_environment.json

    #Frontend Tests
    - language: node_js
      node_js: 10.15
      provider: script
      before_script:
        - docker-compose up -d --build
        - npm install frontend/
      script:
        - docker-compose run --rm frontend npm test src/tests/ -- --coverage
