#Travis Configs File

services:
  - docker

language: node_js

install:
  - docker-compose up -d --build

matrix:
  include:
    - language: python
      python: 3.6
      provider: script
      script:
        - docker-compose run --rm backend ./manage.py test backend/tests/

    - language: node_js
      node_js: 10.15
      provider: script
      script:
        - docker-compose run --rm frontend npm test src/tests/
