#Travis Configs File

language: python

services:
  - docker
  - postgresql

before_install:
  - psql -c 'create database travis_ci_test;' -U postgres

install:
  - docker-compose build

script:
  - docker-compose run --rm backend ./manage.py test backend/tests/
