#Travis Configs File

services:
  - docker

matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - docker-compose up -d --build
      provider: script
      script:
        - docker-compose run --rm backend ./manage.py test backend/tests/

    - language: node_js
      node_js: 10.15
      before_script:
        - docker-compose up -d --build
      provider: script
      script:
        - docker-compose run --rm frontend npm test -- --coverage
