#Travis Config File

services:
  - docker

language: node_js

matrix:
  include:
    #Backend Tests
    - language: python
      python: 3.6
      provider: script
      script:
        - docker-compose run --rm backend ./manage.py test backend/tests/

    #Frontend Tests
    - language: node_js
      node_js: 10.15
      provider: script
      before_script:
        - docker-compose up -d --build
        - npm install frontend/
      script:
        - docker-compose run --rm frontend npm test src/tests/ -- --coverage
