#Travis Configs File

language: python

services:
  - docker

install:
  # - docker-compose build

script:
  - docker-compose run --rm backend ./manage.py test backend/tests/
  - docker-compose run --rm frontend npm test
