#Travis Config File

language: python

services:
  - docker

before_install:
  - docker-compose build
  - docker-compose run --rm backend_travis ./manage.py test backend/tests/
  - pip install -r backend/requirements.txt
