#Travis Configs File

language: python

services:
  - docker
  - postgresql

before_install:
  - "psql -c 'create database myapp_test;' -U postgres"
  - ./manage.py migrate /backend

install:
  - docker-compose build

postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres

script:
  - docker-compose run --rm backend ./manage.py test backend/tests/
