version: "3"

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build: ./backend
    volumes:
      - ./backend/:/backend # maps host directory to internal container directory
    working_dir: /backend/
    command: sh entrypoint.sh
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: sh entrypoint.sh
    working_dir: /frontend
    volumes:
      - ./frontend/:/frontend
  nginx:
    build: ./nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/build:/var/www/frontend
    depends_on:
      - backend

volumes:
  postgres_data: