#This script is for temporary dev server use only. Please do not deploy it in production in its current stage.

version: "3"

#services:
#  emib-db:
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_DB=emib_db
#      - POSTGRES_USER=emib
#      - POSTGRES_PASSWORD=Password1

  backend:
    build: ./backend
    volumes:
      - ./backend/:/backend # maps host directory to internal container directory
    working_dir: /backend/
    command: sh entrypoint.sh
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - DATABASE_NAME=
      - DATABASE_USER=
      - DATABASE_PASSWORD=
      - DATABASE_HOST=
      - DATABASE_PORT=

  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile-server.dev
    ports:
      - 443:443
    depends_on:
      - backend



