#This script is for dev server use.

version: "3"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/backend # maps host directory to internal container directory
    working_dir: /backend/
    command: sh entrypoint.sh
    ports:
      - 8000:8000
    env_file:
      - ./.env

  nginx:
    build:
      context: ./
      dockerfile: dockerfile-frontend-server.dev
    ports:
      - 443:443
    depends_on:
      - backend
