# Generated by Django 2.1.7 on 2019-05-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0003_auto_20190528_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtext',
            name='text_detail',
            field=models.CharField(max_length=3000),
        ),
    ]
