# Generated by Django 2.1.7 on 2019-06-03 15:27
# Edited by J. Michael Cherry to populate the test for the emib sample

from django.db import migrations


def upload_emib_sample(apps, schema_editor):
    # get models
    language = apps.get_model("custom_models", "Language")
    item_text = apps.get_model("custom_models", "ItemText")
    test = apps.get_model("custom_models", "Test")
    # get db alias
    db_alias = schema_editor.connection.alias

    # get emib_sample item
    l_english = (
        language.objects.using(db_alias)
        .filter(ISO_Code_1="en", ISO_Code_2="en-ca")
        .last()
    )
    emib_sample_item_text_en = (
        item_text.objects.using(db_alias)
        .filter(text_detail="eMIB Sample Test", language=l_english)
        .last()
    )

    # create emib sample test model
    # NOTE:
    # the test name ("emibSampleTest") is how we will look up the test
    # the test type ("emib") will also be used for other emib style tests
    # there is also no default time for the sample eMIB
    emib_sample_test = test(
        test_name="emibSampleTest",
        item_id=emib_sample_item_text_en.item_id,
        is_public=True,
        test_type="emib",
    )
    emib_sample_test.save()


def destroy_emib_sample(apps, schema_editor):
    # get models
    test = apps.get_model("custom_models", "Test")
    # get db alias
    db_alias = schema_editor.connection.alias
    # destory the test item created above
    test.objects.using(db_alias).filter(
        test_name="emibSampleTest", is_public=True, test_type="emib"
    ).delete()


class Migration(migrations.Migration):

    dependencies = [("custom_models", "0006_test")]

    operations = [migrations.RunPython(upload_emib_sample, destroy_emib_sample)]
