# Generated by Django 2.1.7 on 2019-06-10 16:12
# Edited by J. Michael Cherry to populate the test for the emib pizza test

from django.db import migrations


def upload_stubbed_pizza(apps, schema_editor):
    # get models
    language = apps.get_model("custom_models", "Language")
    item_type = apps.get_model("custom_models", "ItemType")
    item = apps.get_model("custom_models", "Item")
    test = apps.get_model("custom_models", "Test")
    item_text = apps.get_model("custom_models", "ItemText")

    # get db alias
    db_alias = schema_editor.connection.alias

    # get languages
    l_english = language.objects.using(db_alias).filter(
        ISO_Code_1="en", ISO_Code_2="en-ca").last()
    l_french = language.objects.using(db_alias).filter(
        ISO_Code_1="fr", ISO_Code_2="fr-ca").last()

    # get item_type test
    it_test = item_type.objects.using(db_alias).filter(type_desc="test").last()

    # create pizza test
    # item
    i_pizza = item(item_type_id=it_test, order=1)
    i_pizza.save()

    # test
    pizza_test = test(test_name="emibPizzaTest",
                      item_id=i_pizza,
                      is_public=False, test_type="emib")
    pizza_test.save()

    # item_text
    item_text.objects.using(db_alias).bulk_create([
        item_text(item_id=i_pizza, text_detail="Pizza Test",
                  language=l_english),
        item_text(item_id=i_pizza, text_detail="FR Pizza Test",
                  language=l_french),
    ])


def destroy_stubbed_pizza(apps, schema_editor):
    # get models
    language = apps.get_model("custom_models", "Language")
    item = apps.get_model("custom_models", "Item")
    test = apps.get_model("custom_models", "Test")
    item_text = apps.get_model("custom_models", "ItemText")

    # get db alias
    db_alias = schema_editor.connection.alias

    # get languages
    l_english = language.objects.using(db_alias).filter(
        ISO_Code_1="en", ISO_Code_2="en-ca").last()
    l_french = language.objects.using(db_alias).filter(
        ISO_Code_1="fr", ISO_Code_2="fr-ca").last()

    # get test
    pizza_test = test.objects.using(db_alias).filter(
        test_name="emibPizzaTest", is_public=False, test_type="emib").last()
    # get item
    i_pizza = item.objects.using(db_alias).filter(
        item_id=pizza_test.item_id_id).last()
    # detroy item_text
    item_text.objects.using(db_alias).filter(
        item_id=i_pizza, language=l_english).delete()
    item_text.objects.using(db_alias).filter(
        item_id=i_pizza, language=l_french).delete()
    # destroy test
    pizza_test.delete()
    # destroy item
    i_pizza.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('custom_models', '0009_auto_20190610_0742'),
    ]

    operations = [
        migrations.RunPython(upload_stubbed_pizza, destroy_stubbed_pizza),
    ]
