# Generated by Django 2.1.7 on 2019-06-03 15:27
# Edited by J. Michael Cherry to correct the pizza test time limit

from django.db import migrations


def update_pizza_time(apps, schema_editor):
    # get models
    test = apps.get_model("custom_models", "Test")
    # get db alias
    db_alias = schema_editor.connection.alias

    # correct the pizza test time limit
    pizza_test = test.objects.using(db_alias).filter(test_name="emibPizzaTest").last()
    pizza_test.default_time = 180
    pizza_test.save()


def rollback_pizza_time(apps, schema_editor):
    # get models
    test = apps.get_model("custom_models", "Test")
    # get db alias
    db_alias = schema_editor.connection.alias

    # correct the pizza test time limit
    pizza_test = test.objects.using(db_alias).filter(test_name="emibPizzaTest").last()
    pizza_test.default_time = None
    pizza_test.save()


class Migration(migrations.Migration):

    dependencies = [("custom_models", "0018_upload_pizza_test")]

    operations = [migrations.RunPython(update_pizza_time, rollback_pizza_time)]
