# Generated by Django 2.1.7 on 2019-06-03 15:27
# Edited by J. Michael Cherry to correct the pizza test time limit

from django.db import migrations


def create_new_types(apps, _):
    # get models
    item_type = apps.get_model("custom_models", "ItemType")

    # correct the pizza test time limit
    it_sections = item_type(type_desc="sections")
    it_sections.save()
    it_section = item_type(type_desc="section")
    it_section.save()


def rollback_new_types(apps, schema_editor):
    # get models
    item_type = apps.get_model("custom_models", "ItemType")
    # get db alias
    db_alias = schema_editor.connection.alias

    # delete the types
    item_type.objects.using(db_alias).filter(type_desc="sections").last().delete()
    item_type.objects.using(db_alias).filter(type_desc="section").last().delete()


class Migration(migrations.Migration):

    dependencies = [("custom_models", "0019_pizza_time limit")]

    operations = [migrations.RunPython(create_new_types, rollback_new_types)]
